;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-insert-item
	LaTeX-insert-left-brace
	TeX-font
	TeX-insert-backslash
	electric-newline-and-maybe-indent
	haskell-indentation-common-electric-command
	indent-for-tab-command
	keyboard-escape-quit
	markdown-cycle
	markdown-outdent-or-delete
	))

(setq mc/cmds-to-run-once
      '(
	helm-M-x
	))
